export const ETFS = ['URTH', 'SPY', 'QQQ', 'GLD', '^FCHI'];

export const ETF_CONFIG = {
  URTH: {
    name: 'iShares Global ETF',
    color: '#00d4aa',
    category: 'Global',
  },
  SPY: {
    name: 'S&P 500 ETF',
    color: '#4ecdc4',
    category: 'US Stocks',
  },
  QQQ: {
    name: 'Nasdaq-100 ETF',
    color: '#ff6b6b',
    category: 'Tech Stocks',
  },
  GLD: {
    name: 'Gold ETF',
    color: '#f59e0b',
    category: 'Commodities',
  },
  '^FCHI': {
    name: 'CAC 40 Index',
    color: '#45b7d1',
    category: 'France',
  },
};

export const THEME = {
  bg: {
    primary: '#0a0e27',
    secondary: '#1a1f3a',
    tertiary: '#242d4a',
  },
  text: {
    primary: '#f5f7fa',
    secondary: '#a8b2c7',
  },
  border: '#3a4458',
  accent: '#00d4aa',
  accentAlt: '#00a878',
  success: '#10b981',
  danger: '#ef4444',
  warning: '#f59e0b',
};

export const TRANSLATIONS = {
  FR: {
    welcome: 'Bienvenue sur MarketSync Pro',
    subtitle: 'Analysez les ETF et simulez vos investissements en quelques clics',
    live: 'LIVE',
    updated: 'Mis à jour',
    market: 'Marché',
    analysis: 'Analyse',
    decision: 'Décision',
    signals: 'Signaux du marché',
    buy: 'ACHETER',
    hold: 'CONSERVER',
    sell: 'ALLÉGER',
    simulator: 'Simulateur d\'investissement programmé',
    optimal: 'Allocation optimale',
    exportPdf: 'Export PDF',
    startAnalysis: 'Commencer l\'analyse',
    next: 'Suivant',
    previous: 'Précédent',
    dontShow: 'Ne plus afficher',
    invested: 'Investi',
    finalValue: 'Valeur finale',
    performance: 'Performance',
    annualized: 'Annualisé',
    bestPerf: 'Meilleure perf YTD',
    worstPerf: 'Pire perf YTD',
    avgVolatility: 'Volatilité moyenne',
    avgCorrelation: 'Corrélation avg',
    currentPrice: 'Prix actuel',
    signals: 'Signaux du marché',
    basedOn: 'Basés sur RSI(14), croisement MM20/MM50 et momentum',
  },
  EN: {
    welcome: 'Welcome to MarketSync Pro',
    subtitle: 'Analyze ETFs and simulate your investments in clicks',
    live: 'LIVE',
    updated: 'Updated',
    market: 'Market',
    analysis: 'Analysis',
    decision: 'Decision',
    signals: 'Market Signals',
    buy: 'BUY',
    hold: 'HOLD',
    sell: 'SELL',
    simulator: 'DCA Simulator',
    optimal: 'Optimal Allocation',
    exportPdf: 'Export PDF',
    startAnalysis: 'Start Analysis',
    next: 'Next',
    previous: 'Previous',
    dontShow: 'Don\'t show again',
    invested: 'Invested',
    finalValue: 'Final Value',
    performance: 'Performance',
    annualized: 'Annualized',
    bestPerf: 'Best YTD Performance',
    worstPerf: 'Worst YTD Performance',
    avgVolatility: 'Average Volatility',
    avgCorrelation: 'Avg Correlation',
    currentPrice: 'Current Price',
    signals: 'Market Signals',
    basedOn: 'Based on RSI(14), MA20/MA50 crossover and momentum',
  },
};
